config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'tasks#index'

  resources :tasks 
  resources :projects
  
  
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
    include ActiveModel::Validations

	validates_presence_of :name
end

app/models/task.rb
class Task < ActiveRecord::Base
	validates_presence_of :name 
	belongs_to :project



	default_scope  {order(created_at: :desc)} 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :common_individual_variables, only: [:show, :destroy, :update, :edit]
	before_action :authenticate_user!

	def index
		@projects_all = Project.all 
	end	


	def common_individual_variables
		@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end 	

	def create
	    @project = Project.new(project_params)
	    @project.save
	    redirect_to root_path
	end

	def edit
	end


	def update
		@project = Project.find(params[:id])
		  if @project.update(project_params)
		    redirect_to root_path
		  else
		    render 'edit'
		  end
		end

	def show
	end

	def destroy
		@project.destroy 
		redirect_to root_path 
	end

  private

  def project_params
    params.require(:project).permit(:name, :id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	protect_from_forgery except: :create	

	before_action :common_multiply_variables, only: [:index, :show, :destroy]
	before_action :common_individual_variables, only: [:show, :destroy, :update, :edit]
	before_action :authenticate_user!

	def common_multiply_variables
		@tasks_all = Task.all.order(created_at: :asc)
		@projects_all = Project.all.order(created_at: :asc) 
	end

	def common_individual_variables
		@task = Task.find(params[:id])
	end


	def index
		# binding.pry
		respond_to do |format|
			format.html { @tasks = "Task.all" }
			format.json { render json: "I am a response" }
		end
	end

	def edit
		# redirect_to @task
	end

	# binding.pry
	def create
		# binding.pry
		new_task = Task.create({name: params["name"], due_date: params["due_date"], project_id: params["project_id"]})
		respond_to do |format|
			format.json { render json: new_task}
		end
	end

	def update
	 
	  if @task.update(task_params)
	    redirect_to root_path
	  else
	    render 'edit'
	  end
	end

	def show
	end

	

	def destroy
		@task.destroy 

		redirect_to root_path 
	end

	def create_project
		new_project = Project.create({name: params["name"]})
		respond_to do |format|
			format.json { render json: new_project}
		end
end

	private

	def task_params
		params.require(:task).permit(:name, :due_date, :completed)
	end	



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
	<title>RuG</title>
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
		

</head>
<body>

<div id="user_nav">
	<% if user_signed_in? %>
		<!-- <div id="user_nav_left"> -->
		<div id="user_nav_right">
		<strong><%= current_user.email %></strong> |
		<%= link_to "Settings", edit_user_registration_path %> |
		<%= link_to "Exit", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Registration", new_user_registration_path %> |
		<%= link_to "Login", new_user_session_path %>
	<% end %>
		</div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<div class="wrapper_block">
	<header>
          <h1>Log in</h1>
    </header>
	<div class="task-container">
		<div class="task-header white">
			<div class="task-title">
			</div>
		</div>
		
		<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
		  <div class="form-block">
		  	<%= f.label :email %>
		  	<%= f.email_field :email, autofocus: true %>
		  </div>

		  <div class="form-block">
		  	<%= f.label :password %>
		    <%= f.password_field :password, autocomplete: "off" %>
		</div>

		  <% if devise_mapping.rememberable? -%>
		    <div class="form-block">
		    	<%= f.check_box :remember_me %> <%= f.label :remember_me %>
		    </div>
		  <% end -%>

		  <div class="form-clock text-center">
		  	<%= f.submit "Log in" :id => "add-task", :class => "btn btn-default white" %>
		  </div>
		<% end %>

	<%= render "devise/shared/links" %>
	 
	</div>
</div>




 

app/views/layouts/sign.html.erb
<div class="wrapper_block">
	<header>
          <h1>Sign up</h1>
    </header>
	<div class="task-container">
		<div class="task-header white">
			<div class="task-title">
			</div>
		</div>
		
		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  		<%= devise_error_messages! %>
		  <div class="form-clock">
		  	<%= f.label :email %>
		  	<%= f.email_field :email, autofocus: true %>
		  </div>

		  	<div class="form-clock">
			  	<%= f.label :password %> 
			  	<% if @validatable %>
			  		<i>(<%= @minimum_password_length %> characters minimum)</i>
			  	<% end %>
			    <%= f.password_field :password, autocomplete: "off" %>
			</div>

		  	<div class="form-clock">
			  	<%= f.label :password_confirmation %>
			    <%= f.password_field :password_confirmation, autocomplete: "off" %>
			</div>

		  <div class="form-clock text-center">
		  	<%= f.submit "Sign up" :id => "add-task", :class => "btn btn-default white"%>
		  </div>
		<% end %>
	<%= render "devise/shared/links" %>
	 
	</div>
</div>




 

app/views/projects/edit.html.erb
<div class="wrapper_block">
	<header>
          <h1>Edit</h1>
          <h3><%= @project.name.capitalize %></h3>
    </header>
	<div class="task-container">
		<div class="task-header white">
			<div class="task-title">
				<span class="glyphicon glyphicon-pencil white"></span>
				<h3><%= @project.name.capitalize %></h3>
			</div>
		</div>
		<%= form_for :project, url: project_path(@project), method: :patch do |f| %>
	 
	  	<div class="form-block">
	  		<%= f.label 'Change a name' %>
	    	<%= f.text_field :name %>
	  	</div>
	  	<div class="form-block text-center">
	  		<%= f.submit :id => "add-task", :class => "btn btn-default white" %>
	  	</div>
	 
	<% end %>

	<%= link_to 'Back', root_path, :class => "back" %>
	 
	</div>
</div>




 

app/views/projects/show.html.erb
<div class="wrapper_block">
	<header>
          <h1>Delete</h1>
          <h3><%= @project.name.capitalize %></h3>
    </header>
	<div class="task-container">
		<div class="task-header white">
			<div class="task-title">
				<span class="glyphicon glyphicon-trash white"></span>
				<h3><%= @project.name.capitalize %></h3>
			</div>
		</div>
		<%= form_for :project, url: project_path(@project), method: :patch do |f| %>
	 
	  	<div class="form-block">
	  		<p>Are you sure?</p>
	  	</div>
	  	<div class="form-block text-center">
			
	 
	
	  		
	  	</div>
	 
	<% end %>

	<%= link_to 'Back', root_path, :class => "back" %>
	 
	</div>
</div>




 

app/views/tasks/edit.html.erb
<div class="wrapper_block">
  <header>
          <h1>Edit</h1>
          <h3><%= @task.name.capitalize %></h3>
    </header>
  <div class="task-container">
    <div class="task-header white">
      <div class="task-title">
        <span class="glyphicon glyphicon-pencil white"></span>
        <h3><%= @task.name.capitalize %></h3>
      </div>
    </div>
    <%= form_for :task, url: task_path(@task), method: :patch do |f| %>
      <div class="form-block">
        <%= f.label 'Change a name' %>
      <%= f.text_field :name %>
    <br>
      <%= f.check_box :completed %> 
      <%= f.label "Complete" %>
      </div>
      <div class="form-block text-center">
      
      <%= f.submit :id => "add-task", :class => "btn btn-default white"%>
  
        
      </div>
   
  <% end %>

  <%= link_to 'Back', root_path, :class => "back" %>
   
  </div>
</div>




 

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<title>RuG</title>
	
</head>
<body>

</body>
</html>

    <div class="wrapper_block">
        <header>
          <h1>simple todo lists</h1>
           <h3>from ruby garage</h3>
        </header>
        <div class="task-container">
          <div class="task-header white">
            <div class="task-title">
              <span class="glyphicon glyphicon-calendar white"></span>
              <h3>Add new task</h3>
            </div>
            <!-- <div class="task-controls btn-group btn-group-sm" role="toolbar">
            	<div>
            		<a href="">
	                	<span class="glyphicon glyphicon-pencil white disable"></span>
	              	</a>
            	</div>
            	<div>
            		<a href="">
		                <span id="delete-task" class="glyphicon glyphicon-trash white disable"></span>
		            </a> 
            	</div> 
            </div> -->
          </div>
          <div class="task-body">
            <div class="task-add-row">
              <div class="task-add-inner">
                <span class="glyphicon glyphicon-plus green"></span>
                <div class="input-group">
                  <input type="text" class="form-control" id="name_input" required="required" placeholder="Start typing here to create a task..." required>
                  <div class="styled-select">
                  	<%= select_tag id = "project_id", options_for_select(@projects_all.collect{ |u| [u.name, u.id] }) %>
                  </div>
                  	
                  <span class="input-group-addon green-bg white" id="add_task_button" >Add Task</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% @projects_all.each do |project| %>
	        <div class="task-container">
	        	<div class="task-header white">
		            <div class="task-title">
		              <span class="glyphicon glyphicon-calendar white"></span>
		              <h3><%= project.name %></h3>
		            </div>
		            <div class="task-controls btn-group btn-group-sm" role="toolbar">
		            	<div>
		            		<a href="<%=edit_project_path(project)%>">
		            			<span class="glyphicon glyphicon-pencil white disable"></span>
		            		</a> 
		            	</div>
		              	
		               	<div>
							<%= link_to raw("<span id='delete-task' class='glyphicon glyphicon-trash white disable'></span>"), project_path(project),
							method: :delete,
							data: {confirm: 'Are you sure?'}%>
		               	</div>
		            </div>
		        </div>
		        <% @tasks_all.each do |task| %>
					<% if task.project && task.project.name == project.name %>         
						<div class="added-task-wrapper">
						    <div class="added-task-state">
						      <%= check_box_tag 'done', '1', task.completed%>
						    </div>
						    <div id="name" class="added-task-title">
						      <h4><%= task.name %></h4>
						    </div>
						    <div class="added-task-controls">
						      <!-- <span class="glyphicon glyphicon-sort gray"></span> -->
							    <div>
							    	<a href="<%=edit_task_path(task) %>">
							    		<span class="glyphicon glyphicon-pencil gray"></span>
							    	</a>
							    </div>
							    <div>
							 
							    	<%= link_to raw("<span id='delete-task' class='glyphicon glyphicon-trash gray disable'></span>"), task_path(task),
										method: :delete,
										data: {confirm: 'Are you sure?'}%>
							    </div>  	
						    </div>
						</div>
					<% end %>
				<% end %>	
			</div>
		<% end %>
    </div>


<%= form_for Project.new do |f| %>
  <div class="text-center">
    <%= f.text_field :name, :placeholder => "Enter name of the project"%>
  </div>
  <div class="text-center">
  	<span class="glyphicon glyphicon-plus white"></span>
    <%= f.submit :id => "add-task", :class => "btn btn-default white", :required => "required" %>
  </div>
<% end %>